server:
  port: 8083
spring:
  application:
    name: product-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/online_store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: productdb
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
