server:
  port: 8082

spring:
  application:
    name: order-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/online_store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: orderdb
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
    prometheus:
      enabled: true
logging:
  level:
    io.micrometer.tracing: INFO

