server:
  port: 9296

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IdrisAskarov/online-store-kotlin-config-server.git
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}